-- ============================================================
-- RetroHub Database Schema (VERSI LENGKAP & FINAL)
-- Untuk fresh install: jalankan HANYA file ini di Supabase SQL Editor
-- Tidak perlu file FIX_*.sql lagi — semua sudah digabung di sini
-- ============================================================
-- Versi    : v2.1.6
-- Update   : 2026-06-13
-- ============================================================


-- ============================================================
-- 1. ENUM TYPES
-- ============================================================
CREATE TYPE product_condition AS ENUM ('MIB', 'BIB', 'Loose');
CREATE TYPE transaction_type  AS ENUM ('sale', 'lelang');
CREATE TYPE order_status      AS ENUM (
    'waiting_payment', 'to_ship', 'shipping',
    'delivered', 'completed', 'disputed'
);


-- ============================================================
-- 2. TABEL UTAMA
-- ============================================================

-- A. Profiles (terhubung ke Supabase Auth)
CREATE TABLE public.profiles (
    id                   UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email                TEXT NOT NULL,
    full_name            TEXT NOT NULL,
    store_name           TEXT UNIQUE,

    -- Role: 3 kolom boolean (1 user bisa buyer + seller sekaligus)
    is_buyer             BOOLEAN NOT NULL DEFAULT true,
    is_seller            BOOLEAN NOT NULL DEFAULT false,
    is_admin             BOOLEAN NOT NULL DEFAULT false,
    seller_status        TEXT    DEFAULT NULL, -- NULL | 'pending' | 'active' | 'rejected'

    -- Kontak & verifikasi seller
    whatsapp             TEXT,
    ktp_photo_url        TEXT,
    ktp_selfie_url       TEXT,
    other_store_link     TEXT,

    -- Alamat lengkap
    address_provinsi     TEXT,
    address_provinsi_id  TEXT,
    address_kota         TEXT,
    address_kota_id      TEXT,
    address_kecamatan    TEXT,
    address_kecamatan_id TEXT,
    address_kelurahan    TEXT,
    address_kelurahan_id TEXT,
    address_kodepos      TEXT,
    address_lat          NUMERIC(10,7),
    address_lng          NUMERIC(10,7),
    address_detail       TEXT,
    cart_items           JSONB DEFAULT '[]',

    -- Keuangan
    wallet_balance       NUMERIC(12,2) DEFAULT 0,
    rating               NUMERIC(3,2)  DEFAULT 0,
    reviews_count        INTEGER       DEFAULT 0,

    -- Sistem penalti & suspend
    warning_count        INTEGER   DEFAULT 0,
    suspend_until        TIMESTAMP WITH TIME ZONE,
    penalty_points       INTEGER   NOT NULL DEFAULT 0,
    last_penalty_decay   TIMESTAMP WITH TIME ZONE,

    created_at           TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX idx_profiles_kota     ON public.profiles (address_kota);
CREATE INDEX idx_profiles_kodepos  ON public.profiles (address_kodepos);


-- B. Categories (dikelola admin)
CREATE TABLE public.categories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL UNIQUE,
    icon           TEXT,
    sub_categories JSONB NOT NULL DEFAULT '["Umum"]'::jsonb
);


-- C. Products
CREATE TABLE public.products (
    id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    seller_id        UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title            TEXT NOT NULL,
    description      TEXT,
    category_id      BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
    sub_category     TEXT NOT NULL DEFAULT 'Umum',
    condition        product_condition NOT NULL,
    transaction_type transaction_type  NOT NULL,
    weight_grams     INTEGER NOT NULL DEFAULT 100,
    stock            INTEGER NOT NULL DEFAULT 1,
    price            NUMERIC(12,2),
    starting_bid     NUMERIC(12,2),
    bid_increment    NUMERIC(12,2),
    buyout_price     NUMERIC(12,2),
    duration_hours   INTEGER DEFAULT 24,
    auction_end_time TIMESTAMP WITH TIME ZONE,
    flagged          BOOLEAN NOT NULL DEFAULT false,
    status           TEXT    NOT NULL DEFAULT 'active',
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,

    CONSTRAINT check_pricing CHECK (
        (transaction_type = 'sale'   AND price IS NOT NULL) OR
        (transaction_type = 'lelang' AND starting_bid IS NOT NULL AND bid_increment IS NOT NULL)
    )
);


-- D. Bids (histori penawaran lelang)
CREATE TABLE public.bids (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    bidder_id  UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount     NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);


-- E. Orders (escrow rekber)
CREATE TABLE public.orders (
    id                       UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id               UUID NOT NULL REFERENCES public.products(id)  ON DELETE RESTRICT,
    buyer_id                 UUID NOT NULL REFERENCES public.profiles(id)   ON DELETE RESTRICT,
    seller_id                UUID NOT NULL REFERENCES public.profiles(id)   ON DELETE RESTRICT,

    -- Snapshot produk saat order dibuat
    product_title            TEXT,
    product_description      TEXT,
    product_image_url        TEXT,
    seller_name              TEXT,
    buyer_name               TEXT,

    -- Harga & pembayaran
    price_deal               NUMERIC(12,2) NOT NULL,
    quantity                 INTEGER       NOT NULL DEFAULT 1,
    shipping_cost            NUMERIC(12,2) NOT NULL,
    admin_fee                NUMERIC(12,2) NOT NULL,
    total_payment            NUMERIC(12,2) NOT NULL,
    payment_status           TEXT          NOT NULL DEFAULT 'pending',
    paid_at                  TIMESTAMP WITH TIME ZONE,

    -- Pengiriman
    shipping_courier         TEXT NOT NULL,
    shipping_address         TEXT,
    recipient_name           TEXT,
    recipient_phone          TEXT,
    address_label            TEXT,
    address_patokan          TEXT,
    tracking_number          TEXT,
    shipped_at               TIMESTAMP WITH TIME ZONE,

    -- Status & timeline
    status                   order_status NOT NULL DEFAULT 'waiting_payment',
    seller_accepted_at       TIMESTAMP WITH TIME ZONE,
    delivered_at             TIMESTAMP WITH TIME ZONE,
    completed_at             TIMESTAMP WITH TIME ZONE,
    refunded_at              TIMESTAMP WITH TIME ZONE,

    -- Bukti pengiriman
    buyer_unboxing_video_url TEXT,
    seller_packing_video_url TEXT,

    -- Keuangan seller
    withdrawn_status         TEXT DEFAULT 'available',

    -- Catatan buyer
    buyer_notes              TEXT,

    created_at               TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX idx_orders_buyer_id   ON public.orders(buyer_id);
CREATE INDEX idx_orders_seller_id  ON public.orders(seller_id);
CREATE INDEX idx_orders_status     ON public.orders(status);
CREATE INDEX idx_orders_created_at ON public.orders(created_at DESC);


-- F. Chat Messages
CREATE TABLE public.chat_messages (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    room_id      TEXT NOT NULL,
    sender_id    UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    receiver_id  UUID          REFERENCES public.profiles(id) ON DELETE CASCADE,
    message_text TEXT NOT NULL,
    read         BOOLEAN NOT NULL DEFAULT false,
    media_url    TEXT,
    media_type   TEXT,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);


-- G. Buku Alamat Pengiriman Buyer
CREATE TABLE public.buyer_addresses (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    label           TEXT NOT NULL DEFAULT 'Rumah',
    recipient_name  TEXT NOT NULL,
    recipient_phone TEXT NOT NULL,
    address_detail  TEXT NOT NULL,
    kecamatan       TEXT,
    kota            TEXT,
    provinsi        TEXT,
    kode_pos        TEXT,
    patokan         TEXT,
    is_default      BOOLEAN DEFAULT false,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX idx_buyer_addresses_user_id ON public.buyer_addresses(user_id);


-- H. Disputes (sistem komplain)
CREATE TABLE public.disputes (
    id             TEXT PRIMARY KEY,
    order_id       TEXT NOT NULL,
    buyer_id       UUID NOT NULL REFERENCES public.profiles(id),
    seller_id      UUID NOT NULL REFERENCES public.profiles(id),
    reason         TEXT NOT NULL,
    detail         TEXT NOT NULL,
    photo_urls     JSONB   DEFAULT '[]',
    video_url      TEXT,
    video_filename TEXT,
    video_size_mb  NUMERIC,
    photo_count    INTEGER DEFAULT 0,
    status         TEXT NOT NULL DEFAULT 'pending',
    admin_note     TEXT DEFAULT '',
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    resolved_at    TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_disputes_order_id ON public.disputes(order_id);
CREATE INDEX idx_disputes_buyer_id ON public.disputes(buyer_id);
CREATE INDEX idx_disputes_status   ON public.disputes(status);


-- ============================================================
-- 3. ENABLE ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE public.profiles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bids            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buyer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disputes        ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 4. RLS POLICIES
-- ============================================================

-- PROFILES
CREATE POLICY "Anyone can read profiles"
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = id OR auth.role() = 'service_role');

CREATE POLICY "Users can update their own profile"
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Admins can update any profile"
    ON public.profiles FOR UPDATE USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

CREATE POLICY "Admins can delete profiles"
    ON public.profiles FOR DELETE USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

-- CATEGORIES
CREATE POLICY "Anyone can read categories"
    ON public.categories FOR SELECT USING (true);

CREATE POLICY "Only admins can modify categories"
    ON public.categories FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

-- PRODUCTS
CREATE POLICY "Anyone can read all products"
    ON public.products FOR SELECT USING (true);

CREATE POLICY "Sellers can insert their own products"
    ON public.products FOR INSERT WITH CHECK (
        auth.uid() = seller_id AND EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_seller = true AND seller_status = 'active'
        )
    );

CREATE POLICY "Sellers can update their own products"
    ON public.products FOR UPDATE USING (auth.uid() = seller_id);

CREATE POLICY "Sellers can delete their own products"
    ON public.products FOR DELETE USING (auth.uid() = seller_id);

CREATE POLICY "Admins can manage all products"
    ON public.products FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

-- BIDS
CREATE POLICY "Anyone can read bids"
    ON public.bids FOR SELECT USING (true);

CREATE POLICY "Authenticated buyers can bid"
    ON public.bids FOR INSERT WITH CHECK (
        auth.uid() = bidder_id AND NOT EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND suspend_until > now()
        )
    );

-- ORDERS
CREATE POLICY "Authenticated buyers can create orders"
    ON public.orders FOR INSERT WITH CHECK (auth.uid() = buyer_id);

CREATE POLICY "Involved parties or admin can view order"
    ON public.orders FOR SELECT USING (
        auth.uid() = buyer_id OR auth.uid() = seller_id OR
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

CREATE POLICY "Involved parties or admin can update order"
    ON public.orders FOR UPDATE USING (
        auth.uid() = buyer_id OR auth.uid() = seller_id OR
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

-- CHAT MESSAGES
CREATE POLICY "Users can view chats they are part of"
    ON public.chat_messages FOR SELECT USING (
        auth.uid() = sender_id OR
        room_id LIKE '%' || auth.uid()::text || '%' OR
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

CREATE POLICY "Users can send chats they are part of"
    ON public.chat_messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Receivers can mark their messages as read"
    ON public.chat_messages FOR UPDATE USING (
        auth.uid() = receiver_id
    ) WITH CHECK (
        auth.uid() = receiver_id
    );

-- BUYER ADDRESSES
CREATE POLICY "Users manage own addresses"
    ON public.buyer_addresses FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- DISPUTES
CREATE POLICY "Involved parties can view dispute"
    ON public.disputes FOR SELECT USING (
        auth.uid() = buyer_id OR auth.uid() = seller_id OR
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );

CREATE POLICY "Buyer can create dispute"
    ON public.disputes FOR INSERT WITH CHECK (auth.uid() = buyer_id);

CREATE POLICY "Admin can update dispute"
    ON public.disputes FOR UPDATE USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
    );


-- ============================================================
-- 5. STORAGE BUCKET: dispute-evidence
-- ============================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'dispute-evidence',
    'dispute-evidence',
    true,
    52428800,
    ARRAY['image/jpeg','image/png','image/webp','video/mp4','video/webm','video/quicktime','video/x-msvideo']
)
ON CONFLICT (id) DO UPDATE SET
    public          = true,
    file_size_limit = 52428800;

-- Upload hanya ke path yang diawali dengan dispute ID yang valid
CREATE POLICY "Users upload to their own dispute folder"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (
        bucket_id = 'dispute-evidence' AND
        (storage.foldername(name))[1] IS NOT NULL
    );

CREATE POLICY "Anyone can view dispute evidence"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'dispute-evidence');


-- ============================================================
-- 6. TRIGGER: Sensor Kata Terlarang pada Produk
-- ============================================================
CREATE OR REPLACE FUNCTION public.check_prohibited_words()
RETURNS TRIGGER AS $$
DECLARE
    prohibited_pattern TEXT;
BEGIN
    prohibited_pattern := '\y(hewan|binatang|kucing|anjing|ular|burung|makanan|minuman|cemilan|obat|suplemen|organ|darah|senjata|pistol|pisau|airsoft|judi|slot|chip|bokep|dewasa|porn|narkoba|sabu|ganja|rokok|vape)\y';

    IF (NEW.title ~* prohibited_pattern) OR (NEW.description ~* prohibited_pattern) THEN
        NEW.flagged := true;
    ELSE
        NEW.flagged := false;
    END IF;

    RETURN NEW; -- WAJIB: tanpa ini insert/update dibatalkan diam-diam
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER before_product_insert_update
BEFORE INSERT OR UPDATE ON public.products
FOR EACH ROW EXECUTE FUNCTION public.check_prohibited_words();


-- ============================================================
-- 7. TRIGGER: Auto-create Profile saat User Baru (Google OAuth)
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (
        id, email, full_name, store_name,
        is_buyer, is_seller, is_admin, seller_status
    )
    VALUES (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data->>'full_name', 'User RetroHub'),
        NULL,
        true,
        false,
        (new.email = 'dafiyasinaddafi@gmail.com'),
        NULL
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- 8. TRIGGER: Cegah Manipulasi Harga & Judul Produk
-- ============================================================
CREATE OR REPLACE FUNCTION public.prevent_product_detail_updates()
RETURNS TRIGGER AS $$
DECLARE
    has_orders BOOLEAN;
BEGIN
    IF (OLD.title IS DISTINCT FROM NEW.title OR
        OLD.transaction_type IS DISTINCT FROM NEW.transaction_type)
    THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true
        ) THEN
            RAISE EXCEPTION 'Mengubah judul produk atau jenis transaksi tidak diperbolehkan.';
        END IF;
    END IF;

    IF (OLD.price IS DISTINCT FROM NEW.price OR
        OLD.starting_bid IS DISTINCT FROM NEW.starting_bid OR
        OLD.bid_increment IS DISTINCT FROM NEW.bid_increment OR
        OLD.buyout_price  IS DISTINCT FROM NEW.buyout_price)
    THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true
        ) THEN
            SELECT EXISTS(SELECT 1 FROM public.orders WHERE product_id = OLD.id) INTO has_orders;

            IF has_orders THEN
                IF NEW.price IS NOT NULL AND OLD.price IS NOT NULL AND
                   (NEW.price > OLD.price * 1.5 OR NEW.price < OLD.price * 0.5) THEN
                    RAISE EXCEPTION 'Perubahan harga maksimal +/-50%% karena produk ini sudah memiliki histori transaksi.';
                END IF;
                IF NEW.starting_bid IS NOT NULL AND OLD.starting_bid IS NOT NULL AND
                   (NEW.starting_bid > OLD.starting_bid * 1.5 OR NEW.starting_bid < OLD.starting_bid * 0.5) THEN
                    RAISE EXCEPTION 'Perubahan harga awal lelang maksimal +/-50%% karena produk ini sudah memiliki histori transaksi.';
                END IF;
                IF NEW.buyout_price IS NOT NULL AND OLD.buyout_price IS NOT NULL AND
                   (NEW.buyout_price > OLD.buyout_price * 1.5 OR NEW.buyout_price < OLD.buyout_price * 0.5) THEN
                    RAISE EXCEPTION 'Perubahan harga buyout maksimal +/-50%% karena produk ini sudah memiliki histori transaksi.';
                END IF;
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER trigger_prevent_product_detail_updates
BEFORE UPDATE ON public.products
FOR EACH ROW EXECUTE FUNCTION public.prevent_product_detail_updates();


-- ============================================================
-- SELESAI — Database RetroHub siap digunakan.
-- Tidak perlu menjalankan file FIX_*.sql lagi.
-- ============================================================
